#include <algorithm>
#include <iostream>
#include <optional>
#include <string>
#include <vector>
#include <queue>
#include <unordered_map>
#include <memory>
#include <functional>
#include <map>
using namespace std;

// enum subject {
//     HINDI,
//     ENLISH,
//     MATH
// };

class Student{
public:
    string name;
    string ID;
    map <string, int> marks;

    Student(){};
    Student(string name, string id)
    : name(name), ID(id){};
};

class Classroom{
public:
    int classID;
    vector<string> studentIDs;
    map<string, Student&> class_map;

    Classroom(int id) : classID(id){};

    void addStudent(string name, string ID){
        class_map[ID] = Student(name, ID);
        studentIDs.push_back(ID);
    }

    void addMarks(string id, string subject, int marks){
        if(class_map.find(id) != class_map.end()){
            Student& currStudent = class_map[id];
            currStudent.marks[subject] = marks;
        } else{ 
            cout << "no such student bsdk" << endl;
        }
    }

    void ranking(string strategy, string subject, int top = 1){
        if(strategy == "highest"){
            HighestMarks::getHighest(*this, subject);
        } else {
            // 
        }
    }
};

class RankingStrategy{
    Student topper;
    virtual void printRanking(Classroom &classroom1, string subject) = 0;
};

class HighestMarks : RankingStrategy {
    void printRanking(Classroom &room, string subject){
        for(auto StudentItem: room.class_map){
            Student currStudent = StudentItem.second;
            if (!topper){
                topper = currStudent;
            }
            else if (topper.marks[subject] < currStudent.marks[subject]){
                topper = currStudent;
            } 
        }

        cout << topper.id << endl;
    }
};

class GetRanking :: RankingStrategy {
    static void printRanking(Classroom &room, string subject){
        
    }
};

int main(){
    
    return 0;
}

/*

Siddhant Panda
E001B
ENG 50
MATH 60


Raghuvir Singh
A410
HINDI 60
ENG 70

-> given a student, how much they scored in a given subject?
-> given a subject, who scored the highest? 
-> can this change? Ranking etc? --> yes
-> can there be multiple classrooms? --> yes
-> should the ID be autogenerated? --> NO
-> Is there a defined set of subjects? --> yes, but not all compulsory
-> can the marks be doubles? --> only int
-> tie? return ANYONE
-> duplicate entry for same [ID + SUBJECT] -> OVERRIDE

*/